spring.application.name=kyc-verification-system
spring.datasource.url=jdbc:postgresql://localhost:5432/kyc_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB

spring.mvc.async.request-timeout=-1
server.tomcat.connection-timeout=600000

aws.region=ap-south-1
aws.accessKeyId=AKIAR6HY5FFACIMOLTO7
aws.secretAccessKey=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

liveness.confidence.threshold=80.0

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
upload.directory=uploads

server.error.include-message=always
server.error.include-binding-errors=always

logging.level.com.kyc=DEBUG
logging.level.org.springframework.web.cors=DEBUG
