-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT username_uk UNIQUE (username)
)

TABLESPACE pg_default;

INSERT INTO users (id, name, username) VALUES
(1, 'Aishwarya Naik', 'aishwarya'),
(2, 'Devdutt Padikkal', 'devdutt'),
(3, 'Virat Kohli', 'virat');